### ISSUE TITLE
Create Page for the Question and Answer in the Morning

### ISSUE THREAD

**Issue by marialitwa** [marialitwa/capstone-project#1]
## Value Proposition

**As a user**
**I want to** ask myself what I’m looking forward to today
**so that** I can start my day with a positive feeling.

## Description
![Image](https://user-images.githubusercontent.com/31568593/201892430-784d3c5f-5f03-49ff-b092-2577cf21f3dd.png)

## Acceptance Criteria
- when opening the app the user sees the question “Worauf freue ich mich heute?”
- the user can type his/her answer into a text field and save it
- when the user clicks on the save button the answer is displayed in a list underneath the form

## Tasks
- [ ]  open feature branch
- [ ]  create a form element with label showing the morning question 
- [ ]  inside the form create textarea element for the answer
- [ ]  add submit button with useState to display the answer with onClick handler
- [ ]  create a `QuestionCard` component
- [ ]  Research useState and localStorage

## Complexity 
M

**Happy coding!** 🙂
