### ISSUE TITLE
Add media queries to morning and evening page

### ISSUE THREAD

**Issue by marialitwa** [marialitwa/capstone-project#16]
## Value Proposition
**As a** user
**I want to** have an appealing and functional design of the morning and evening pages on different screen sizes
**so that I** can use the app in a convenient way on several devices 

## Description
![Image](https://github.com/marialitwa/capstone-project/assets/31568593/17fd81ec-4043-4e91-a23a-ad66649a2aa0)

## Acceptance Criteria
- the design of the morning and evening pages adapts responsively to different screen sizes 
- the user can switch between different devices without a loss of design quality

## Tasks
- [ ] open feature branch
- [ ] add media queries for a small and a large screen size to the morning page
- [ ] add media queries for a small and a large screen size to the evening page

## Complexity 
S
