### ISSUE TITLE
Create Evening Page and Home Page

### ISSUE THREAD

**Issue by marialitwa** [marialitwa/capstone-project#2]
## Value Proposition

**As a user**
**I want to** ask myself what was the best of the day today
**so that** I can end my day with a positive feeling before going to sleep.

## Description
![Image](https://user-images.githubusercontent.com/31568593/201901583-e2e1082b-8dca-4677-a399-da0c7b39a63b.png)
![Image](https://user-images.githubusercontent.com/31568593/201901660-cb107c7e-cf2d-44b1-a0c6-3c7d9df94187.png)

## Acceptance Criteria
- the user sees the question “Was war heute das Beste des Tages?”
- the user can type his/her answer into a text field and save it
- when the user clicks on the save button the answer is displayed in a list underneath the form
- the user can navigate to a homepage respectively from the Morning Page and the Evening Page
- the homepage has two buttons and on the top it displays the current weekday and date (day+month)
- homepage: when the user clicks the button "Frage am Morgen" he/she navigates to the Morning Question/Answer Page 
- homepage: when the user clicks the button "Frage am Abend" he/she navigates to the Evening Question/Answer Page 

## Tasks
- [ ]  open feature branch
- [ ]  reuse the Question Component from the morning question and adapt it to the evening question adding props
- [ ]  create Home Page with two buttons
- [ ]  link the buttons with Next.js page routing to the Morning Page and the Evening Page on click
- [ ]  create Go Back Home Button/Icon with Next.js page routing within the Question Component
- [ ]  the Go Back Home Icon is displayed on the Morning Page and the Evening Page
- [ ]  the Go Back Button it is placed on the left top corner
- [ ]  Research how to display Day, Date and Month
- [ ]  use get.Date() JS-Method to display the current date
- [ ]  use get.Day() JS-Method to display the current weekday in line with the current date
- [ ]  create Day+Date Component

## Complexity 
L

**Happy coding!** 🙂

**Comment by BucherLara** [comment]
Huhu Maria, tolle App Idee :-)  ich finde die value proposition etwas zu ungenau, vielleicht:
...so that I can [save them] and end my day with a positive feeling before going to sleep, damit die Funktion deiner App herauskommt. 
Acceptance Criteria: .. navigate to **the** homepage, ist ja deine homepage und nicht eine. Ich würde die Navigation nicht als buttons bezeichnen, sondern navigations-items, dass klar ist dass das deine Navigation ist. Und ich würde den button und die Funktion des buttons zusammenschreiben und etwas weiter oben, was auf der Homepage zu sehen ist : ...and on the top it displays the current weekday and date (day+month). Und im Wireframe 1 ist ein Pfeil zurück, kommt der schon aus Userstory 1 oder ist das damit gemeint (the user can navigate to a homepage respectively from the Morning Page and the Evening Page) ?

**Comment by marialitwa** [comment]
Thanks for your attentive feedback, Lara 👍 I've adopted your suggestions, hope it's a bit more clear now 😊

**Comment by marialitwa** [comment]
Thanks Meena, for your feedback! :) I think it's up to yourself whether you use bullet points or checkboxes. I wrote it the same way in my user story #1 and the coaches accepted it :)
