### ISSUE TITLE
Create Show Answer Page

### ISSUE THREAD

**Issue by marialitwa** [marialitwa/capstone-project#5]
## Value Proposition

**As a user**
**I want to** only see my answers on a single page
**so that** I can focus on my positive thoughts about the day

## Description
![Image](https://user-images.githubusercontent.com/31568593/203021535-d5cbaddb-d4fd-4cdd-b074-bcb8a4e32f08.png)

## Acceptance Criteria
- the user sees the question and his/her answer from the morning and the evening on a seperate single page
- the entry date (the day when the answer was entered) is displayed
- the user can navigate between his/her answers from other days
- the entry date is changing correspondingly
- the user can navigate from the homepage to the page with the answers and back to home

## Tasks
- [ ]  open feature branch
- [ ]  create 'ShowAnswer' page
- [ ]  create `MorningAnswer` component
- [ ]  create `EveningAnswer` component
- [ ]  add nav item on the homepage linking to the show answer page
- [ ]  add nav item to go back to homepage
- [ ]  create `Footer` with navigation 
- [ ]  add navigation routing to switch between the entries/show anwser pages
- [ ]  use .getDate() and connect the corresponding date to the entries

## Complexity 
L

**Comment by MeenaFoerderer** [comment]
Nice feature! :) Just two small typos: (1) in the value proposition 'user' should not be bold, (2) in the acceptance criteria: separate instead of seperate.

**Comment by marialitwa** [comment]
Thank you @MeenaFoerderer for your feedback! :)
