### ISSUE TITLE
Select Your Favorites

### ISSUE THREAD

**Issue by marialitwa** [marialitwa/capstone-project#6]
## Value Proposition

**As a** user
**I want to** select my favorite answers and have them displayed on a separate page
**so that** I can scroll through my best moments and enjoy this empowering motivation booster.

## Description
![Image](https://user-images.githubusercontent.com/31568593/203575475-9982297f-55ef-4382-a915-8d84b01f61d6.png)

## Acceptance Criteria
- the user can click a favorite icon on the show answer page 
- by clicking it the answer from that day is selected as a favorite
- all favorites are displayed on a separate page 
- the favorites list is sorted by the latest entry date
- from the favorites list page the user can navigate back in a natural flow via the show answer page to the homepage 
- from the homepage the user can navigate directly to the favorites list page clicking the filter icon
- the favs list page has a filter icon so that the user knows he/she is on a filtering page

## Tasks
- [x] open feature branch
- [x] install React Icons with command `npm install react-icons --save`
- [x] add a favorite icon to Show Answer Page
- [x] add a link from homepage to favorites page and back to homepage
- [x] create a new page for the favorites list 
- [x] add a navigation item to show answer page
- [x] use filter method to filter all favorites and display all favorites on the favs list page
- [x] use sort method to sort the favs by the latest entry 
- [x] add basic styling

## Complexity 
L

**Comment by marialitwa** [comment]
Thanks for your lovely feedback! Makes me happy 🥰 
That's a good point regarding the navigation flow, I was thinking about that as well. I'm not sure yet which way is better, but will start as described for now. When I feel it feels more natural to navigate straight to the homepage I'll definitely adjust that 🙂 
Also, I'll put a thought on the style of the filter icon on these two pages, haven't done that yet. Thanks for your input, much appreciated! 🙏
