### ISSUE TITLE
Add Evening Color Scheme

### ISSUE THREAD

**Issue by marialitwa** [marialitwa/capstone-project#9]
## Value Proposition
**As a** user
**I want to** have a dark color theme for the evening hours
**so that I** can get into an evening mode and my eyes are not strained by bright light.

## Description
![Image](https://user-images.githubusercontent.com/31568593/204540753-dc5cae7d-e317-4224-b152-9b59b1b36eb2.png)

## Acceptance Criteria
- the app has a second blueish-purplish Evening Color Theme 
- the color of texts and icons is light grayish/white
- the accessibility regarding the contrast should be considered
- the user can switch between two color themes

## Tasks
- [ ] open feature branch
- [ ] create new dark color theme 
- [ ] add toggle button with useEffect to switch between for dark and light mode
- [ ] alternative 1 to toggle button: the dark and light mode changes automatically at 6am and 6pm
- [ ] alternative 2 to toggle button: the color scheme changes with a weather API fetch, fetching the time of the local sunrise and sunset

## Complexity 
M

**Comment by FelineHuhn** [comment]
You could show the toggle button for switching the color theme in a wireframe too, but otherwise everything perfect!

**Comment by marialitwa** [comment]
You're right! Thanks for your thoughts, Feline 😊 Initially I did plan a weather API fetch, so that the dark and light mode would change automatically with sunrise and sunset. Which is why I didn't add a toggle button in the design template at first 🙂
